[package]
name = "clue"
version = "1.0.93"
description = "C/Rust like programming language that compiles into Lua code (BETA)\nMade by Felix44\nhttps://github.com/Felix-44/Clue"
edition = "2018"
build = "build.rs"
authors = ["Felix44"]

[build-dependencies]
winres = "0.1"

[dependencies]
clap = {version = "3.1.6", features = ["derive"]}